-- Content seed: the 38 sub-stressor taxonomy and the full 114-row
-- (38 x 3 energy levels) action matrix, transcribed from
-- SPARK_Master_Action_Matrix_Sub_Stressor_Map.pdf. This is the real
-- feeling-to-task mapping (EPIC 1) that Linu's backlog items were blocked
-- on -- delivered directly as a document rather than landed in Notion.

insert into sub_stressors (code, pillar, label, sort_order) values
  ('SOC_01', 'social', 'Conversation Paralysis', 1),
  ('SOC_02', 'social', 'Fear of Rejection', 2),
  ('SOC_03', 'social', 'Dining Hall Solo Anxiety', 3),
  ('SOC_04', 'social', 'FOMO / Feeling Left Out', 4),
  ('SOC_05', 'social', 'Roommate Tension', 5),
  ('SOC_06', 'social', 'Large Crowd Overwhelm', 6),
  ('SOC_07', 'social', 'Club Intimidation', 7),
  ('SOC_08', 'social', 'Social Battery Exhaustion', 8),
  ('SOC_09', 'social', 'Hometown Disconnection', 9),
  ('SOC_10', 'social', 'Group Dynamic Exclusivity', 10),
  ('EDU_01', 'education', 'Exam / Midterm Panic', 1),
  ('EDU_02', 'education', 'Procrastination Paralysis', 2),
  ('EDU_03', 'education', 'Presentation Dread', 3),
  ('EDU_04', 'education', 'Group Project Tension', 4),
  ('EDU_05', 'education', 'Professor Intimidation', 5),
  ('EDU_06', 'education', 'Imposter Syndrome', 6),
  ('EDU_07', 'education', 'Lecture Backlog', 7),
  ('EDU_08', 'education', 'Major Uncertainty', 8),
  ('EDU_09', 'education', 'Grade Disappointment', 9),
  ('EDU_10', 'education', 'Study Space Monotony', 10),
  ('CAR_01', 'career', 'Networking Intimidation', 1),
  ('CAR_02', 'career', 'Rejection Fatigue', 2),
  ('CAR_03', 'career', 'Resume Blank Page Syndrome', 3),
  ('CAR_04', 'career', 'Career Fair Overwhelm', 4),
  ('CAR_05', 'career', 'Interview Anxiety', 5),
  ('CAR_06', 'career', 'Post-Grad Path Dread', 6),
  ('CAR_07', 'career', 'Peer Comparison', 7),
  ('CAR_08', 'career', 'Cover Letter Burnout', 8),
  ('CAR_09', 'career', 'Portfolio Stagnation', 9),
  ('CAR_10', 'career', 'Unclear Skill Alignment', 10),
  ('HLT_01', 'health_personal', 'Low Energy / Fatigue', 1),
  ('HLT_02', 'health_personal', 'Sleep Disruption', 2),
  ('HLT_03', 'health_personal', 'Homesickness / Adjustment', 3),
  ('HLT_04', 'health_personal', 'Doomscrolling / Tech Fatigue', 4),
  ('HLT_05', 'health_personal', 'Gym Intimidation', 5),
  ('HLT_06', 'health_personal', 'Routine Collapse', 6),
  ('HLT_07', 'health_personal', 'Financial Stress', 7),
  ('HLT_08', 'health_personal', 'Overwhelm / Brain Clutter', 8)
on conflict (code) do nothing;

insert into action_matrix (substressor_code, energy_level, action_text) values
  ('SOC_01', 1, 'Read 1 conversation starter prompt in the app to save for later.'),
  ('SOC_01', 2, 'Send a quick meme or text to a friend you haven''t spoken to this week.'),
  ('SOC_01', 3, 'Say "good morning" or ask a quick question to the person sitting next to you in class.'),
  ('SOC_02', 1, 'Write down 1 low-stakes campus activity you''d enjoy doing with a peer.'),
  ('SOC_02', 2, 'Send an open-ended "Thinking of you, hope exams go well!" text.'),
  ('SOC_02', 3, 'Invite a classmate to grab coffee before class or post a 2-person hangout on SPARK.'),
  ('SOC_03', 1, 'Listen to a podcast or music playlist while eating lunch at a quiet table.'),
  ('SOC_03', 2, 'Sit at a communal dining table near others without looking at your phone for 5 minutes.'),
  ('SOC_03', 3, 'Ask a peer if an empty chair at their table is open, or post an open lunch invite on SPARK.'),
  ('SOC_04', 1, 'Take 2 minutes to list 3 activities you genuinely enjoy doing solo.'),
  ('SOC_04', 2, 'Browse the SPARK Event board and bookmark 1 upcoming activity to join later.'),
  ('SOC_04', 3, 'Post a spontaneous low-key invite on SPARK (e.g., "Heading to the student lounge for 30 mins").'),
  ('SOC_05', 1, 'Complete a 2-minute box-breathing exercise in your room to calm frustration.'),
  ('SOC_05', 2, 'Leave a polite sticky note or send a short, friendly text regarding shared chores.'),
  ('SOC_05', 3, 'Initiate a 2-minute in-person check-in with your roommate using a neutral, supportive tone.'),
  ('SOC_06', 1, 'Step outside a noisy event for a 3-minute quiet break in the fresh air.'),
  ('SOC_06', 2, 'Stand or sit near the exit perimeter with a bottle of water to regulate sensory load.'),
  ('SOC_06', 3, 'Attend a small-group meetup on SPARK capped at 2-3 people instead of a large gathering.'),
  ('SOC_07', 1, 'Browse the campus club directory and bookmark 1 organization that matches an interest.'),
  ('SOC_07', 2, 'Save an upcoming official club event post on SPARK to your personal calendar.'),
  ('SOC_07', 3, 'Attend an official club meeting or join an official club event posted on SPARK.'),
  ('SOC_08', 1, 'Put your phone on ''Do Not Disturb'' and close your eyes for a 3-minute audio reset.'),
  ('SOC_08', 2, 'Send a polite, templated raincheck text ("Low energy today, let''s connect Friday!").'),
  ('SOC_08', 3, 'Take a 10-minute solo recharge walk across a quiet campus path.'),
  ('SOC_09', 1, 'Look at a favorite photo from home and send a 1-sentence text to a family member.'),
  ('SOC_09', 2, 'Voice-note a hometown friend for 1 minute updating them on your week.'),
  ('SOC_09', 3, 'Schedule a brief weekend call or post on SPARK looking for fellow out-of-state students.'),
  ('SOC_10', 1, 'Write down 1 unique personal strength or hobby you bring to campus life.'),
  ('SOC_10', 2, 'Comment supportively on a peer''s post on the SPARK Campus Feed.'),
  ('SOC_10', 3, 'Create or join a 1-on-1 SPARK meetup based on a specific niche interest.'),

  ('EDU_01', 1, 'Complete a 2-minute guided box-breathing exercise on the reset tab.'),
  ('EDU_01', 2, 'Write down the top 3 specific topics you need to review on a blank sheet of paper.'),
  ('EDU_01', 3, 'Post or join an Education study group event on SPARK for an upcoming exam.'),
  ('EDU_02', 1, 'Open your project document and type just 1 sentence or title heading.'),
  ('EDU_02', 2, 'Set a timer for 5 minutes and work continuously on 1 task until the alarm sounds.'),
  ('EDU_02', 3, 'Pair up with an optional SPARK Buddy to do a 15-minute async focus session.'),
  ('EDU_03', 1, 'Do a 2-minute physical shoulder-drop and slow exhalation sequence.'),
  ('EDU_03', 2, 'Practice the first 30 seconds of your presentation speech aloud in private.'),
  ('EDU_03', 3, 'Present your opening slide to a friend or SPARK study buddy for quick feedback.'),
  ('EDU_04', 1, 'Outline your assigned part of the project in 3 clear bullet points.'),
  ('EDU_04', 2, 'Send a concise update message to the group chat stating what you will complete today.'),
  ('EDU_04', 3, 'Host or join a 20-minute SPARK group project work session in the library.'),
  ('EDU_05', 1, 'Draft 1 specific question about class material in your notes app.'),
  ('EDU_05', 2, 'Email your professor or TA asking for clarification on a single assignment detail.'),
  ('EDU_05', 3, 'RSVP or walk in to office hours to ask your drafted question in person.'),
  ('EDU_06', 1, 'Read 3 stigma-normalizing peer quotes in the SPARK resource hub.'),
  ('EDU_06', 2, 'Write down 2 academic achievements or tough assignments you completed in the past.'),
  ('EDU_06', 3, 'Share an honest reflection or join a study group on SPARK to see peers facing similar struggles.'),
  ('EDU_07', 1, 'Select 1 missed lecture video and open it on your screen without pressing play yet.'),
  ('EDU_07', 2, 'Watch 5 minutes of a recorded lecture at 1.25x speed and take 2 brief notes.'),
  ('EDU_07', 3, 'Set up a "Catch-Up" co-working session with a peer or SPARK study buddy.'),
  ('EDU_08', 1, 'Jot down 3 topics or classes that have felt most engaging so far this semester.'),
  ('EDU_08', 2, 'Search your department website for an academic advisor or advisor contact email.'),
  ('EDU_08', 3, 'Book an appointment with an academic advisor or attend a major exploration club session.'),
  ('EDU_09', 1, 'Close the grade portal and take 5 deep breaths to decompress.'),
  ('EDU_09', 2, 'Review the assignment to highlight 2 specific mistakes you can learn from next time.'),
  ('EDU_09', 3, 'Message a TA or professor to schedule a brief 5-minute review of your assignment rubric.'),
  ('EDU_10', 1, 'Stretch at your desk and look out a window for 60 seconds.'),
  ('EDU_10', 2, 'Pack your bag and walk to a different floor or new campus building to study.'),
  ('EDU_10', 3, 'Join a SPARK library study group post located at a new campus location.'),

  ('CAR_01', 1, 'Search for 1 school alumnus on LinkedIn and read their career path summary.'),
  ('CAR_01', 2, 'Save a draft connection note on LinkedIn without pressing send yet.'),
  ('CAR_01', 3, 'Send a 2-sentence LinkedIn connection request to an alumnus asking for a brief chat.'),
  ('CAR_02', 1, 'Read an in-app prompt: "My worth is not tied to an automated application response."'),
  ('CAR_02', 2, 'Log into your application spreadsheet and archive rejected entries to clear visual clutter.'),
  ('CAR_02', 3, 'Post a supportive reflection on the SPARK feed or connect with a peer navigating job hunting.'),
  ('CAR_03', 1, 'Download a clean, standard resume template and save it to your desktop.'),
  ('CAR_03', 2, 'Write down 2 bullet points describing responsibilities from a recent class project or job.'),
  ('CAR_03', 3, 'Visit campus career center drop-in hours or review resumes with a SPARK buddy.'),
  ('CAR_04', 1, 'Bookmark 3 target companies attending the career fair in the campus portal.'),
  ('CAR_04', 2, 'Spend 3 minutes practicing your elevator pitch aloud in private.'),
  ('CAR_04', 3, 'Post or join a Career event on SPARK to walk into the career fair alongside a peer buddy.'),
  ('CAR_05', 1, 'Read 1 common behavioral interview question and outline a 3-bullet answer.'),
  ('CAR_05', 2, 'Record yourself answering 1 interview question on your phone and listen back once.'),
  ('CAR_05', 3, 'Complete a 10-minute mock interview run-through with a friend or SPARK career buddy.'),
  ('CAR_06', 1, 'List 2 short-term personal goals for the upcoming month instead of 5 years out.'),
  ('CAR_06', 2, 'Bookmark 1 entry-level job posting or graduate program page that looks interesting.'),
  ('CAR_06', 3, 'Attend a career services workshop or join a career-focused group event on SPARK.'),
  ('CAR_07', 1, 'Read an in-app prompt: "Everyone''s career timeline is completely unique."'),
  ('CAR_07', 2, 'Unfollow or mute professional updates on social media for 24 hours to reduce stress.'),
  ('CAR_07', 3, 'Connect 1-on-1 with a SPARK peer to discuss real-world career struggles openly.'),
  ('CAR_08', 1, 'Copy-paste a basic cover letter outline into a fresh document draft.'),
  ('CAR_08', 2, 'Customize the company name and 1 specific reason why you admire their product/team.'),
  ('CAR_08', 3, 'Swap cover letter drafts with a SPARK peer buddy for a quick 5-minute review swap.'),
  ('CAR_09', 1, 'Create a "Portfolio Projects" folder and gather files from 2 past assignments.'),
  ('CAR_09', 2, 'Write a 3-sentence summary describing the core problem and solution for 1 project.'),
  ('CAR_09', 3, 'Post a link or screenshot of your project on SPARK''s feed for constructive peer feedback.'),
  ('CAR_10', 1, 'Find 1 target job description and highlight 3 required skills you already possess.'),
  ('CAR_10', 2, 'Identify 1 skill gap and bookmark a free 15-minute online tutorial or module.'),
  ('CAR_10', 3, 'Attend a campus club skill workshop posted on the SPARK event board.'),

  ('HLT_01', 1, 'Step outside your dorm/building and take 5 deep breaths in fresh air.'),
  ('HLT_01', 2, 'Drink a full glass of water and stretch for 2 minutes away from your desk.'),
  ('HLT_01', 3, 'Go for a 10-minute walk across campus without checking social media.'),
  ('HLT_02', 1, 'Set an alarm for tonight''s wind-down routine (e.g., 30 mins before sleep).'),
  ('HLT_02', 2, 'Move your phone across the room 15 minutes before bed and do a 2-minute audio grounding track.'),
  ('HLT_02', 3, 'Pair up with a SPARK sleep-accountability buddy to send a nightly "screens off" ping.'),
  ('HLT_03', 1, 'Set a favorite photo from home as your lock screen or look at a home memory.'),
  ('HLT_03', 2, 'Send a brief voice message or text update to a family member or home friend.'),
  ('HLT_03', 3, 'Join a SPARK meetup for out-of-state or first-year students grabbing tea or coffee.'),
  ('HLT_04', 1, 'Close all social media apps and place your phone face down for 5 minutes.'),
  ('HLT_04', 2, 'Swap screen time for a 3-minute music track with your eyes closed.'),
  ('HLT_04', 3, 'Leave your phone in your room while taking a short walk to the campus center.'),
  ('HLT_05', 1, 'Look up campus rec center hours and quiet/off-peak times online.'),
  ('HLT_05', 2, 'Do a 3-minute bodyweight stretch or routine in the privacy of your room.'),
  ('HLT_05', 3, 'Post or join a "Gym Buddy" event on SPARK to visit the rec center together.'),
  ('HLT_06', 1, 'Write down 1 single non-negotiable task to do today (e.g., make bed or drink water).'),
  ('HLT_06', 2, 'Block out your next 2 hours on paper into 30-minute focus chunks.'),
  ('HLT_06', 3, 'Pair with a SPARK buddy to share your top 2 priorities for the day.'),
  ('HLT_07', 1, 'Take 2 minutes to list your essential campus expenses for the week on paper.'),
  ('HLT_07', 2, 'Research 1 free campus meal or student resource event happening this week.'),
  ('HLT_07', 3, 'Attend a free campus event or meal hosted by a student club on SPARK.'),
  ('HLT_08', 1, 'Do a 2-minute "brain dump" on paper: write down everything without organizing.'),
  ('HLT_08', 2, 'Circle the single most important task on your brain dump list and hide the rest.'),
  ('HLT_08', 3, 'Complete a sub-3-minute guided grounding or breathing exercise on SPARK.')
on conflict (substressor_code, energy_level) do nothing;
